
when:
  - event:
      - push
    path:
      include: [".woodpecker/build-image.yaml", ".woodpecker/Dockerfile"]
      ignore_message: "[ALL]"
  - event:
      - manual

steps:
  publish-image-branch:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: codeberg.org/${CI_REPO_OWNER}/sveltekit-robinopletal-buildimage
      registry: codeberg.org
      platforms: linux/amd64,linux/arm64/v8
      dockerfile: .woodpecker/Dockerfile
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
    when:
      evaluate: CI_COMMIT_BRANCH != CI_REPO_DEFAULT_BRANCH

  publish-image-latest:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: codeberg.org/${CI_REPO_OWNER}/sveltekit-robinopletal-buildimage
      registry: codeberg.org
      platforms: linux/amd64,linux/arm64/v8
      tags: latest, ${CI_COMMIT_SHA}
      dockerfile: .woodpecker/Dockerfile
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
    when:
      evaluate: CI_COMMIT_BRANCH == CI_REPO_DEFAULT_BRANCH
