
when:
  - event:
    - push
    - manual
  - evaluate: 'CI_PIPELINE_EVENT == "push" && CI_REPO == "${CI_REPO_OWNER}/ansible-play-dockerhost" && CI_COMMIT_BRANCH == CI_REPO_DEFAULT_BRANCH'

steps:
  publish-image-branch:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: codeberg.org/${CI_REPO_OWNER}/robinopletal.com
      registry: codeberg.org
      tags: ${CI_COMMIT_SHA}
      # platforms: linux/amd64,linux/arm64/v8
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
    when:
      evaluate: CI_COMMIT_BRANCH != CI_REPO_DEFAULT_BRANCH

  publish-image-latest:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: codeberg.org/${CI_REPO_OWNER}/robinopletal.com
      registry: codeberg.org
      # platforms: linux/amd64,linux/arm64/v8
      tags: latest, ${CI_COMMIT_SHA}
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
    when:
      evaluate: CI_COMMIT_BRANCH == CI_REPO_DEFAULT_BRANCH
